---
- name: Pull docker image
  hosts: all
  tasks:
    - name: Pull ngonexus-react image
      docker_image:
        name: asthaborkataky/ngonexusfront
        source: pull
    - name: Pull ngonexus-spring image
      docker_image:
        name: asthaborkataky/ngonexusback
        source: pull
    - name: copy Docker Compose files
      copy:
        src: docker-compose.yml
        dest: ./