
version: '3.3'

services:
  #service 1: definition of mysql database
  db:
    image: mysql/mysql-server:latest
    container_name: mysql-db2
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
    ports:
      - "3306:3306"
    restart: always
  frontend:
    image: asthaborkataky/ngonexus-react:latest
    build: ./Nexus
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  #service 3: definition of your spring-boot app
  ngonexus:                        #it is just a name, which will be used only in this file.
    image: asthaborkataky/ngonexus-react                #name of the image after dockerfile executes
    container_name: ngonexus  #name of the container created from docker image
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - "8888:8888"                       #docker container port with your os port
    restart: always

    depends_on:                           #define dependencies of this app
      - db                                #dependency name (which is defined with this name 'db' in this file earlier)
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/tgl?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password