version: "3.7"
services:
  dbse:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ngggonexus
    ports:
      - 3307:3306
    volumes:
      - db:/var
  frontend:
    image: asthaborkataky/ngonexusfront
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
  backend:
    image: asthaborkataky/ngonexusback
    depends_on:
      - dbse
    expose:
      - "8089"
    restart: on-failure:10
    ports:
      - 8089:8089
    volumes:
      - img:/home
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://dbse:3306/ngggonexus?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "password",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver"
      }'
volumes:
  db:
  img: